### ISSUE TITLE
缺少Jar包

### ISSUE THREAD

**Issue by ywmmmw** [xishuixixia/Hetty#2]
Exception in thread "main" java.lang.NoClassDefFoundError: org/jaxen/JaxenException
    at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:230)
    at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:207)
    at org.dom4j.tree.AbstractNode.selectNodes(AbstractNode.java:164)
    at com.hetty.conf.XmlConfigParser.getRoot(XmlConfigParser.java:165)
    at com.hetty.conf.XmlConfigParser.<init>(XmlConfigParser.java:35)
    at com.hetty.plugin.XmlConfigPlugin.start(XmlConfigPlugin.java:21)
    at com.hetty.core.Hetty.initPlugins(Hetty.java:142)
    at com.hetty.core.Hetty.init(Hetty.java:53)
    at com.hetty.core.Hetty.start(Hetty.java:240)
    at org.fxl.test.Test.main(Test.java:12)
Caused by: java.lang.ClassNotFoundException: org.jaxen.JaxenException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 10 more
使用过程中会报这样一个异常,查询资料,原因是dom4j需要jaxen包导致的
http://www.jaxen.org/

**Comment by ywmmmw** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassWriter
    at com.esotericsoftware.reflectasm.MethodAccess.get(MethodAccess.java:85)
    at com.hetty.object.ServiceProvider.<init>(ServiceProvider.java:25)
    at com.hetty.conf.XmlConfigParser.parseService(XmlConfigParser.java:94)
    at com.hetty.plugin.XmlConfigPlugin.start(XmlConfigPlugin.java:28)
    at com.hetty.core.Hetty.initPlugins(Hetty.java:142)
    at com.hetty.core.Hetty.init(Hetty.java:53)
    at com.hetty.core.Hetty.start(Hetty.java:240)
    at org.fxl.test.Test.main(Test.java:12)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassWriter
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 8 more
http://sourceforge.net/projects/cglib/
