### ISSUE TITLE
入门级问题 望解答

### ISSUE THREAD

**Issue by aChenspring** [xishuixixia/Hetty#4]
Exception in thread "main" com.caucho.hessian.client.HessianConnectionException: HessianProxy cannot connect to 'http://localhost:8081/apis/hello/
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:139)
	at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:283)
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:170)
	at com.sun.proxy.$Proxy0.hello(Unknown Source)
	at com.hetty.Test.main(Test.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.FileNotFoundException: http://localhost:8081/apis/hello/
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:122)
	... 9 more
Caused by: java.io.FileNotFoundException: http://localhost:8081/apis/hello/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:109)
	... 9 more

Process finished with exit code 1

**Comment by aChenspring** [comment]
客户端调用时发生的错误，谢谢

**Comment by mindotektpm** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

jackhhh, @wwek, @xxx7xxxx, @hshq, @yujiangshui, @thewashingtonhua, @liuyufei, @ustbhuangyi, @KeKe-Li, @abciknow, @KyrinCode, @hoyunfei, @jkeylu, @azhong, @Evllis, @yeslsl, @wu191287278, @yxw839841231, @zwmagic, @ljk99

**Comment by KyrinCode** [comment]
Received.Kyrin
